### ISSUE TITLE
Logins don't work for restricted people

### ISSUE THREAD

**Issue by RealistikDash** [RealistikOsu/pep.py#1]
# Login Issue for Restricted Players
## Background on the issue
Users that do not have the `PUBLIC` privilege (aka restricted users) are unable to log into RealisitkOsu. This is due to one of my overhaul commits, where the `restricted` status was changed into a property (meaning that the status is always verified rather than being set on initial login, which offers the benefit of allowing for privilege refreshes).

## The issue
Now, while having noticable benefits, this causes issues in areas where the change was overlooked, where one place is login. The code attempts to set the value on login, which causes an error and results in a permanent loading thing client side.

## Code referenced
Restricted property:
https://github.com/RealistikOsu/pep.py/blob/dc83684bb57a9761e1a4062539d624a96dfafbb0/objects/osuToken.py#L116-L120

Attempted redefenition (causing the actual error):
https://github.com/RealistikOsu/pep.py/blob/dc83684bb57a9761e1a4062539d624a96dfafbb0/objects/osuToken.py#L562

**Comment by tsunyoku** [comment]
Fix can be found here: https://github.com/RealistikOsu/pep.py/pull/2

**Comment by RealistikDash** [comment]
Solved with #2
